tests: s390: use r0 as scratch register
The 'param_test' test on s390 uses 'r12' as a scratch register which is not a
general purpose register and is used to store the GOT pointer [1]. This
resulted in build failures:

  In function ‘rseq_load_cbne_store__ptr_relaxed_cpu_id’,
      inlined from ‘rseq_load_cbne_store__ptr’ at ../include/rseq/rseq.h:248:10,
      inlined from ‘rseq_this_cpu_lock’ at param_test.c:431:9,
      inlined from ‘test_percpu_spinlock_thread’ at param_test.c:467:13:
  ../include/rseq/arch/s390/bits.h:20:9: error: PIC register clobbered by ‘r12’ in ‘asm’
     20 |         __asm__ __volatile__ goto (

Use 'r0' instead which is documented as general purpose and recommend
for use in inline assembly.

[1] https://refspecs.linuxbase.org/ELF/zSeries/lzsabi0_s390.html#AEN417

Change-Id: I38085b15cd2f6ee0b8fc0692ed1b01af11bffb87
Signed-off-by: Michael Jeanson <mjeanson@efficios.com>
Signed-off-by: Mathieu Desnoyers <mathieu.desnoyers@efficios.com>